### ISSUE TITLE
Error: No such device or address

### ISSUE THREAD

**Issue by sumitridhal** [angular-buch/angular-cli-ghpages#23]
Getting this error. Kindly suggest.
OS: Window 10

ng build --prod --base-href "https://sumitridhal.github.io/the-new-school/"
ngh --no-silent

```
An error occurred!
 { Error
    at ChildProcess.<anonymous> (C:\Users\Sumit Ridhal\AppData\Roaming\npm\node_modules\angular-cli-ghpages\node_modules\gh-pages\lib\git.js:47:23)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:897:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
  code: 128,
  message: 'bash: /dev/tty: No such device or address\nerror: failed to execute prompt script (exit code 1)\nfatal: could not read Username for \'https://github.com\': Invalid argument\n',
  name: 'ProcessError' }
```

**Comment by sumitridhal** [comment]
Duplicate [#14](https://github.com/angular-buch/angular-cli-ghpages/issues/14)
