### ISSUE TITLE
Causes `ng build` error (can't resolve module @angular/core/src/di/opaque_token)

### ISSUE THREAD

**Issue by JohannesHoppe** [angular-buch/angular-cli-ghpages#3]
```
can't resolve module @angular/core/src/di/opaque_token from DIR\src\index.ts
symbol.getDeclarations is not a function
TypeError: symbol.getDeclarations is not a function
    at ReflectorHost.findDeclaration (DIR\node_modules\@angular\compiler-cli\src\reflector_host.js:179:38)
    at StaticReflector.initializeConversionMap (DIR\node_modules\@angular\compiler-cli\src\static_reflector.js:145:38)
    at new StaticReflector (DIR\node_modules\@angular\compiler-cli\src\static_reflector.js:42:14)
    at AotPlugin._setupOptions (DIR\node_modules\@ngtools\webpack\src\plugin.js:137:27)
    at new AotPlugin (DIR\node_modules\@ngtools\webpack\src\plugin.js:37:14)
    at Object.exports.getWebpackNonAotConfigPartial (DIR\node_modules\angular-cli\models\webpack-build-typescript.js:20:13)
    at new NgCliWebpackConfig (DIR\node_modules\angular-cli\models\webpack-config.js:23:42)
    at Class.run (DIR\node_modules\angular-cli\tasks\build-webpack.js:17:22)
    at Class.run (DIR\node_modules\angular-cli\commands\build.js:54:26)
    at Class.<anonymous> (DIR\node_modules\angular-cli\angular-cli\lib\models\command.js:152:17)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by JohannesHoppe** [comment]
closed by https://github.com/angular-buch/angular-cli-ghpages/commit/5beb8a6da6e9bb64430eef34ccd8528f2067bad3
